version: '3'

services:
  helloworld:
    image: ts-express-api-rest-helloworld-docker-compose-single-image
    container_name: ts-express-api-rest-helloworld-docker-compose-single-container
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - helloworld-network

networks:
  helloworld-network:
    name: helloworld-network-name